FROM python:3.6.2

# Create app directory
WORKDIR /code

# Geting the code from current directory
COPY . .

# Install app dependencies
RUN pip install -r requirements.txt

#CMD [ "python", "./main.py" ]
