version: '2'
services:
  web:
    build: .
    container_name: 'gunicorn_webserver'
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: 1
    command: gunicorn -w 1 -t 90 -b 0.0.0.0:5000 main:app --log-config logging.conf
